streams:
  testcam: rtsp://rtsp-test:8554/test

  # Camera 1 placeholders
  cam1_main: rtsp://USERNAME:PASSWORD@CAM1_IP:554/cam/realmonitor?channel=1&subtype=0
  cam1_sub: rtsp://USERNAME:PASSWORD@CAM1_IP:554/cam/realmonitor?channel=1&subtype=1

  # Camera 2 placeholders
  cam2_main: rtsp://USERNAME:PASSWORD@CAM2_IP:554/cam/realmonitor?channel=1&subtype=0
  cam2_sub: rtsp://USERNAME:PASSWORD@CAM2_IP:554/cam/realmonitor?channel=1&subtype=1

