services:
  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    ports:
      - "1984:1984"
      - "8554:8554"
      - "8555:8555"
    volumes:
      - ../config/go2rtc.yaml:/config/go2rtc.yaml:ro
    restart: unless-stopped
    networks:
      - localbox

  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ../data/homeassistant:/config
    environment:
      - TZ=${TZ}
    ports:
      - "8123:8123"
    restart: unless-stopped
    networks:
      - localbox
    depends_on:
      - go2rtc

  rtsp-test:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-test
    restart: unless-stopped
    networks:
      - localbox

  rtsp-publisher:
    image: jrottenberg/ffmpeg:6.1-alpine
    container_name: rtsp-publisher
    restart: unless-stopped
    networks:
      - localbox
    depends_on:
      - rtsp-test
    command:
      - -re
      - -stream_loop
      - "-1"
      - -i
      - https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
      - -c
      - copy
      - -f
      - rtsp
      - rtsp://rtsp-test:8554/test

networks:
  localbox:
    driver: bridge

